config/routes.rb
Rails.application.routes.draw do
  root 'postings#index'
  resources :postings, only: [:create, :show]

     get 'confirmation' => 'static_pages#confirmation'
     get 'submit' => 'postings#new'
     

     
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  validates_presence_of :title, :description, :location, :ptype, :deadline
  validate :check_ptype

  def check_ptype
  	errors.add(:ptype, "Cannot be this value") if (self.ptype != "full_time" && self.ptype != "part_time" && self.ptype != "internship")
  end
  
  def self.search(params)
  	postings = self.all
  	postings = postings.where("deadline > ?", Time.now).order(:deadline)
  	postings = postings.where("title like ? ", "%#{params[:title]}%") if params[:title].present?
  	postings = postings.where("location like ? ", "%#{params[:location]}%") if params[:location].present?
  	if params[:ptype].present?
  	  postings = postings.where("ptype != 'full_time'") if params[:full_time] == "0"
  	  postings = postings.where("ptype != 'part_time'") if params[:part_time] == "0"
  	  postings = postings.where("ptype != 'internship'") if params[:internship] == "0"
  	end
  	return postings
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posting_controller.rb
class PostingController < ApplicationController
  def new
  end

  def create
  end

  def show
    @posting = Posting.find(params[:id])
  end

  def index
    @postings = Posting.all
  end

end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  def new
    @posting = Posting.new
  end

  def create
    @posting = Posting.new(posting_params)

    if @posting.save
      flash[:notice] = "Event Created!"
      redirect_to root_path
    else 
      render 'new'
    end
  end

  def show
    @posting = Posting.find(params[:id])
  end

  def index
    searchpar = Posting.search(params)
    @postings = searchpar.paginate(:page => params[:page])
    @results_found = searchpar.length
  end

  private

    def posting_params
      params.require(:posting).permit(:title, :location, :ptype, :description, :deadline)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def confirmation
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posting_helper.rb
module PostingHelper
	def get_opportunity_type(ptype)
		if ptype == "full_time"
			return "Full Time"
						
		elsif ptype == "part_time"
			return "Part Time"
						
		else ptype == "internship"
			return "Internship"	
		end 
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EclubCareer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/navigation_bar" %>

<div class="container">
  <% flash.each do |key, value| %>
    <% if key.to_s == "notice" %>
      <div class="alert alert-<%= key %> alert-success"><%= value %></div>
    <% elsif key.to_s == "alert" %>
      <div class="alert alert-<%= key %> alert-danger"><%= value %></div>
    <% else %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  <% end %>
  
  <%= yield %>
</div>

<%= render "partials/footer_bar" %>

</body>
</html>

app/views/partials/_navigation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to image_tag('gloriousleader.jpg', :alt => "logo", :class => "logo"), root_path %></li>
        <li><%= link_to "Browse", root_path %></li>
        <li><%= link_to "Submit", submit_path %></li>
        
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_posting.html.erb
<div class="posting">
	<div class="posting-left"> 
		<div class="posting-title">
			<%= link_to(posting.title, posting) %>
		</div>

		<div class="posting-description line-clamp">
			<%= posting.description.truncate(80, separator: ' ') %>
		</div>

		<div>
			<div class="posting-tagbox <%= posting.ptype %>">
				<%= get_opportunity_type(posting.ptype) %>
			</div>
		</div>
	</div>

	<div class="posting-location">
		<%= posting.location %>
	</div>

	<div class="posting-date">
		<%= posting.deadline.to_date.to_formatted_s(:long_ordinal) %>
	</div>
</div>

app/views/partials/_search.html.erb
<div class="search-box">
  <%= bootstrap_form_tag url: "/", method: "get" do |f| %>
    <%= f.text_field(:title, value: params[:title]) %>

    <%= f.form_group :ptype, label: { text: "Opportunity Type" } do %>
        <%= f.check_box(:full_time, label: "Full Time", checked: true) %>
        <%= f.check_box(:part_time, label: "Part Time", checked: true) %>
        <%= f.check_box(:internship, label: "Internship", checked: true) %>
    <% end %>

    <%= f.text_field(:location, value: params[:location]) %>
    <%= f.submit("Search") %>
  <% end %>
</div>

app/views/postings/index.html.erb
<h1>Search Postings</h1>
<%= render partial: 'partials/search' %>

<h1>Listing Postings</h1>
<div class="results"> <%= pluralize(@results_found, "Result") %> Found </div> <br>

<%= will_paginate @postings %>
<%= render partial: 'partials/posting', collection: @postings %>
<%= will_paginate @postings %>

app/views/postings/new.html.erb
Thank you for using the Princeton E-Club Career Website. Please submit your positing and expect it to be live within 2-3 days!

<div class="full-page-form col-md-offset-3 col-md-6">
  <center><h1 class="form-header">Submit an Opportunity</h1></center>
  <div class="form">
		<%= bootstrap_form_for(@posting) do |f| %>
		  <%= f.alert_message "You cannot submit because of the following errors:" %>
		  <div>
			<div class="new-posting-field">
			  <%= f.label :title %>
			  <%= f.text_field :title, :autofocus => true, hide_label: true, placeholder: "Insert the Title of The Opportunity..."%>
			</div>
		  <hr>
		  <div class="new-posting-field">
			  <%= f.label :location %>
			  <%= f.text_field :location, hide_label: true , placeholder: "Location of the Opportunity..."%>
		  </div>
		  <hr>
		  <div class="new-posting-field">
			  <%= f.label :description %>
			  <%= f.text_area :description, hide_label: true, placeholder: "Insert a comprehensive description..." %>
			</div> 
		  <hr>
			<div class="new-posting-field">
			  <%= f.label "Opportunity Type" %>
		    <%= f.select(:ptype, options_for_select([['Full-Time', "full_time"], ['Part-Time', "part_time"], ['Internship', "internship"]]), hide_label: true) %>
			</div>
		  <hr>
		  <div class="new-posting-deadline">
		    <%= f.label :deadline %>
		    <%= f.date_select :deadline, hide_label: true %>
		  </div>
		  <hr>
		  <%= submit_tag("Submit", :class => 'btn btn-large btn-primary') %>
		<% end %> 
  </div>

app/views/postings/show.html.erb
<div class="show-wrapper">
	<div class="show-header">
		<div class="show-title">
			<h2><%= @posting.title %></h2>
		</div>
		<div class="show-details">
			<div class="posting-tagbox <%= @posting.ptype %>">
				<%= get_opportunity_type(@posting.ptype) %>
			</div>
			<%= @posting.location %>
			<%= @posting.deadline.to_date.to_formatted_s(:long_ordinal) %>
		</div>
	</div>
	<hr>
	<div class="show-body">
		<%= simple_format(@posting.description) %>
	</div>
</div>

app/views/static_pages/confirmation.html.erb
You have confirmed! 

app/views/static_pages/home.html.erb
Hello World!